version: "3.9"

services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: rehab-iot-timescale
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - db-data:/var/lib/postgresql/data
    networks: [appnet]


  redis:
    image: redis:7-alpine
    container_name: rehab-iot-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks: [appnet]

  ingest-api:
    build:
      context: ./ingest
      dockerfile: Dockerfile
    container_name: ingest-api
    expose:
      - "8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - appnet

  iot-api:
    build:
      context: ./backend
      dockerfile: backend-iot/Dockerfile
    container_name: rehab-iot-api-server
    restart: unless-stopped
    depends_on: [db, redis]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TZ: Asia/Seoul

      # Postgres JDBC
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      # Redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    expose:
    - "8080"
    networks: [appnet]

  user-api:
    build:
      context: ./backend
      dockerfile: backend-user/Dockerfile
    container_name: rehab-user-api-server
    restart: unless-stopped
    depends_on: [db, redis]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TZ: Asia/Seoul

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    expose:
      - "80"
    networks: [appnet]

  frontend:
    build: ./frontend
    container_name: rehab-frontend-ui
    restart: unless-stopped
    depends_on: [iot-api, user-api]
    ports:
      - "3000:80"
    networks: [appnet]

  nginx:
    image: nginx:alpine
    container_name: rehab-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
      - ./nginx/certs:/etc/letsencrypt:ro
    depends_on:
      - user-api
    networks:
      - appnet
    restart: always

  certbot:
    image: certbot/certbot
    container_name: rehab-certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certs:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM;
             while :; do
               certbot renew;
               sleep 12h;
             done"

networks:
  appnet:

volumes:
  db-data:
  redis-data:
