
server {
    listen 80;
    server_name i14a203.p.ssafy.io;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 "http ok\n";
    }
}