spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rehab
    username: app
    password: G2WhXPnBrUR2tVPMC5pphBERTDY
  jpa:
    hibernate:
      ddl-auto: update

# 예: 외부 API 키는 로컬에서만
server:
  port: 8083
tts:
  api-key: "PUT_YOUR_KEY_HERE"
