// backend/backend-user/build.gradle
bootJar { enabled = true }
jar { enabled = false }

dependencies {
    implementation project(':common-db')

    implementation 'org.springframework.boot:spring-boot-starter-web'

    runtimeOnly 'com.h2database:h2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}